### PR TITLE
Use the correct ctor for NodeDetailsCollector

### LINKED ISSUE #164: Handle empty string in cluster setting update
For the config overrides cluster settings, we currently see the following stacktrace during startup caused due to empty string being tried to be parsed as JSON.
```
 com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
elasticsearch2    |  at [Source: ; line: 1, column: 0]
elasticsearch2    |    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.8.11.jar:2.8.11]
elasticsearch2    |    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3854) ~[jackson-databind-2.8.11.jar:2.8.11]
elasticsearch2    |    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799) ~[jackson-databind-2.8.11.jar:2.8.11]
elasticsearch2    |    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858) ~[jackson-databind-2.8.11.jar:2.8.11]
elasticsearch2    |    at com.amazon.opendistro.elasticsearch.performanceanalyzer.config.overrides.ConfigOverridesHelper.lambda$deserialize$1(ConfigOverridesHelper.java:75) ~[performanceanalyzer-rca-1.3.jar:?]
elasticsearch2    |    at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
elasticsearch2    |    at com.amazon.opendistro.elasticsearch.performanceanalyzer.config.overrides.ConfigOverridesHelper.deserialize(ConfigOverridesHelper.java:73) ~[performanceanalyzer-rca-1.3.jar:?]
elasticsearch2    |    at com.amazon.opendistro.elasticsearch.performanceanalyzer.config.setting.handler.ConfigOverridesClusterSettingHandler.onSettingUpdate(ConfigOverridesClusterSettingHandler.java:60) [opendistro_performance_analyzer-1.3.0.0-SNAPSHOT.jar:1.3.0.0-SNAPSHOT]
elasticsearch2    |    at com.amazon.opendistro.elasticsearch.performanceanalyzer.config.setting.handler.ConfigOverridesClusterSettingHandler.onSettingUpdate(ConfigOverridesClusterSettingHandler.java:35) [opendistro_performance_analyzer-1.3.0.0-SNAPSHOT.jar:1.3.0.0-SNAPSHOT]
elasticsearch2    |    at com.amazon.opendistro.elasticsearch.performanceanalyzer.config.setting.ClusterSettingsManager.callStringSettingListeners(ClusterSettingsManager.java:234) [opendistro_performance_analyzer-1.3.0.0-SNAPSHOT.jar:1.3.0.0-SNAPSHOT]
elasticsearch2    |    at com.amazon.opendistro.elasticsearch.performanceanalyzer.config.setting.ClusterSettingsManager.access$400(ClusterSettingsManager.java:29) [opendistro_performance_analyzer-1.3.0.0-SNAPSHOT.jar:1.3.0.0-SNAPSHOT]
elasticsearch2    |    at com.amazon.opendistro.elasticsearch.performanceanalyzer.config.setting.ClusterSettingsManager$ClusterSettingsResponseHandler.onResponse(ClusterSettingsManager.java:270) [opendistro_performance_analyzer-1.3.0.0-SNAPSHOT.jar:1.3.0.0-SNAPSHOT]
elasticsearch2    |    at com.amazon.opendistro.elasticsearch.performanceanalyzer.config.setting.ClusterSettingsManager$ClusterSettingsResponseHandler.onResponse(ClusterSettingsManager.java:245) [opendistro_performance_analyzer-1.3.0.0-SNAPSHOT.jar:1.3.0.0-SNAPSHOT]
elasticsearch2    |    at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68) [elasticsearch-7.3.2.jar:7.3.2]
elasticsearch2    |    at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64) [elasticsearch-7.3.2.jar:7.3.2]
elasticsearch2    |    at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:54) [elasticsearch-7.3.2.jar:7.3.2]
elasticsearch2    |    at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1101) [elasticsearch-7.3.2.jar:7.3.2]
elasticsearch2    |    at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:224) [elasticsearch-7.3.2.jar:7.3.2]
elasticsearch2    |    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.3.2.jar:7.3.2]
elasticsearch2    |    at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:193) [elasticsearch-7.3.2.jar:7.3.2]
elasticsearch2    |    at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:216) [elasticsearch-7.3.2.jar:7.3.2]
elasticsearch2    |    at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:141) [elasticsearch-7.3.2.jar:7.3.2]
elasticsearch2    |    at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105) [elasticsearch-7.3.2.jar:7.3.2]
elasticsearch2    |    at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660) [elasticsearch-7.3.2.jar:7.3.2]
elasticsearch2    |    at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) [transport-netty4-client-7.3.2.jar:7.3.2]
elasticsearch2    |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar:4.1.36.Final]
elasticsearch2    |    at java.lang.Thread.run(Thread.java:834) [?:?]
```

While this is benign, we should have better handling of empty string values.

### LINKED ISSUE #165: Node details collector fails to write events to the serial log
Node details collector is not writing any events to the event log. This is causing the reader to not parse node details and therefore causing RCA framework to not start.

### PR DESCRIPTION
**Pull request by ktkrg**
*Issue #, if available:*
Fixes #165 
Fixes #164 

*Description of changes:*
The NodeDetailsCollector instantiation in the plugin was overwritten by change #162 

This change instantiates the node details collector correctly.
This change also gets rid of the confusing stacktrace that gets printed during ES startup.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/setting/handler/ConfigOverridesClusterSettingHandler.java [hunk 1]
```diff
@@ -57,9 +57,13 @@ public ConfigOverridesClusterSettingHandler(final ConfigOverridesWrapper overrid
     @Override
     public void onSettingUpdate(String newSettingValue) {
         try {
-            final ConfigOverrides newOverrides = ConfigOverridesHelper.deserialize(newSettingValue);
-            overridesHolder.setCurrentClusterConfigOverrides(newOverrides);
-            overridesHolder.setLastUpdatedTimestamp(System.currentTimeMillis());
+            if (newSettingValue != null && !newSettingValue.isEmpty()) {
```
Comment (vigyasharma) [inline src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/setting/handler/ConfigOverridesClusterSettingHandler.java:60]: Can we add a UT for this?

File: src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java [hunk 2]
```diff
@@ -188,7 +188,7 @@ public PerformanceAnalyzerPlugin(final Settings settings, final java.nio.file.Pa
 
         scheduledMetricCollectorsExecutor.addScheduledMetricCollector(new MetricsPurgeActivity());
 
-        scheduledMetricCollectorsExecutor.addScheduledMetricCollector(new NodeDetailsCollector());
```
Comment (vigyasharma) [inline src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java:191]: Can we remove this default constructor from `NodeDetailsCollector`, or is it required?

Comment (ktkrg) [reply src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/PerformanceAnalyzerPlugin.java:191]: Let me check the usages. Maybe the no arg constructor is not used anymore.

File: src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/setting/handler/ConfigOverridesClusterSettingHandler.java (hunk 1 above)
Comment (ktkrg) [reply src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/config/setting/handler/ConfigOverridesClusterSettingHandler.java:60]: I will add a UT for this.
